version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.462.2
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins_init:/usr/share/jenkins/ref/init.groovy.d
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=bazinga
    restart: unless-stopped
    mem_limit: 3g

volumes:
  jenkins_home:
